export const GET_TRADER_PROFILE = 'GET_TRADER_PROFILE';
export const GET_TRADER_SUCCESS_PROFILE = 'GET_TRADER_SUCCESS_PROFILE';
export const CLEAR_GET_TRADER_PROFILE_STATE = 'CLEAR_GET_TRADER_PROFILE_STATE';
export const API_ERROR = 'LOGIN_API_ERROR';
