export const GET_BRANDS = 'GET_BRANDS';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const API_ERROR = 'LOGIN_API_ERROR';
export const CLEAR_GET_BRANDS_STATE = 'CLEAR_GET_BRANDS_STATE';
