export const GET_TRADERS = 'GET_TRADERS';
export const GET_TRADER_SUCCESS = 'GET_TRADER_SUCCESS';
export const CLEAR_GET_TRADERS_STATE = 'CLEAR_GET_TRADERS_STATE';
export const API_ERROR = 'LOGIN_API_ERROR';
