export const GET_CUSTOM_FIELDS = 'GET_CUSTOM_FIELDS';
export const GET_CUSTOM_FIELDS_SUCCESS = 'GET_CUSTOM_FIELDS_SUCCESS';

export const API_ERROR = 'CUSTOM_FIELDS_API_ERROR';

export const CLEAR_GET_CUSTOM_FIELDS_STATE = 'CLEAR_GET_CUSTOM_FIELDS_STATE';
