export enum Country {
  Spain = 'spain',
  Ireland = 'ireland',
  Australia = 'australia',
  Austria = 'austria',
  Bahrain = 'bahrain',
  Belgium = 'belgium',
  Canada = 'canada',
  Denmark = 'denmark',
  Finland = 'finland',
  France = 'france',
  Germany = 'germany',
  Portugal = 'portugal',
  Poland = 'poland',
  Lithuania = 'lithuania',
  Italy = 'italy',
  Phillipines = 'phillipines',
  Netherlands = 'netherlands',
  CzechRepublic = 'czechRepublic',
  Norway = 'norway',
  Singapore = 'singapore',
  Sweden = 'sweden',
  Switzerland = 'switzerland',
  UnitedArabEmirates = 'unitedArabEmirates',
  UnitedKingdom = 'unitedKingdom',
  Malaysia = 'malaysia',
  Luxembourg = 'luxembourg',
  Comoros = 'comoros',
}

export const CountryLabel = {
  [Country.Spain]: 'Spain',
  [Country.Ireland]: 'Ireland',
  [Country.Australia]: 'Australia',
  [Country.Austria]: 'Austria',
  [Country.Bahrain]: 'Bahrain',
  [Country.Belgium]: 'Belgium',
  [Country.Canada]: 'Canada',
  [Country.Denmark]: 'Denmark',
  [Country.Finland]: 'Finland',
  [Country.France]: 'France',
  [Country.Germany]: 'Germany',
  [Country.Portugal]: 'Portugal',
  [Country.Poland]: 'Poland',
  [Country.Lithuania]: 'Lithuania',
  [Country.Italy]: 'Italy',
  [Country.Phillipines]: 'Phillipines',
  [Country.Netherlands]: 'Netherlands',
  [Country.CzechRepublic]: 'Czech Republic',
  [Country.Norway]: 'Norway',
  [Country.Singapore]: 'Singapore',
  [Country.Sweden]: 'Sweden',
  [Country.Switzerland]: 'Switzerland',
  [Country.UnitedArabEmirates]: 'United Arab Emirates',
  [Country.UnitedKingdom]: 'United Kingdom',
  [Country.Malaysia]: 'Malaysia',
  [Country.Luxembourg]: 'Luxembourg',
  [Country.Comoros]: 'Comoros',
};

export const CountryListOptions = Object.entries(CountryLabel).map(
  ([value, label]) => ({
    value,
    label,
  }),
);

export const CountryValueList = CountryListOptions.map((value) => value.value);
