export enum PaymentMethod {
  BTC = 'BTC',
  KORXONET_Raiffeisen = 'KORXONET_Raiffeisen',
  ALGORITMO_Mill = 'ALGORITMO_Mill',
  PayCent = 'PayCent',
  PSP_Neobanq = 'PSP_Neobanq',
  PSP_NextPay = 'PSP_NextPay',
  RoyalCoins = 'RoyalCoins',
  Ontario_CIBC = 'Ontario_CIBC',
  Oceanlive_MB = 'Oceanlive_MB',
  EclipCoin = 'EclipCoin',
  Famas_ING = 'Famas_ING',
  CoinCash_Sent = 'CoinCash_Sent',
  CORISMA_RAIFFEISEN = 'CORISMA_RAIFFEISEN',
  Miracle_Montepio = 'Miracle_Montepio',
  WiseNex = 'WiseNex',
  GRASPARAW_RAIFFEISEN = 'GRASPARAW_RAIFFEISEN',
  CUBERKS_SANTANDER = 'CUBERKS_SANTANDER',
  KEYTECHAGES_RAIFFEISEN = 'KEYTECHAGES_RAIFFEISEN',
  Fábulas_Novo = 'Fábulas_Novo',
  Centorina_BBVA = 'Centorina_BBVA',
  CPS_BTC = 'CPS_BTC',
  ECLETICSUND_ING = 'ECLETICSUND_ING',
  Avangard_Unicredit = 'Avangard_Unicredit',
  Keinter_Raiffeisen = 'Keinter_Raiffeisen',
  Carisma_Novo = 'Carisma_Novo',
  ErithExchange = 'ErithExchange',
  Randomsoft_SANTANDER = 'Randomsoft_SANTANDER',
  Ferbalix_Raiffeisen = 'Ferbalix_Raiffeisen',
  SOFTSOLCOMP_SANTANDER = 'SOFTSOLCOMP_SANTANDER',
  CompSoftCar_CAIXA = 'CompSoftCar_CAIXA',
  QUOTIDIAN_CRUSADE_ABANCA = 'QUOTIDIAN_CRUSADE_ABANCA ', // TODO-FIX: remove space. change enum in db
  QUOTIDIAN_CRUSADE_BPI = 'QUOTIDIAN_CRUSADE_BPI',
  GesimaDecision_BBVA = 'GesimaDecision_BBVA',
  PSP_BridgerPay = 'PSP_BridgerPay',
  Pinolitex_Santander = 'Pinolitex_Santander',
  Flamingo_Crusade = 'Flamingo_Crusade',
  LTC = 'LTC',
  LIZER_TECHNOLOGY = 'LIZER_TECHNOLOGY',
  Andolantra_SI = 'Andolantra_SI',
}

export const PaymentMethodLabel = {
  [PaymentMethod.BTC]: 'BTC',
  [PaymentMethod.KORXONET_Raiffeisen]: 'KORXONET(Raiffeisen)',
  [PaymentMethod.ALGORITMO_Mill]: 'ALGORITMO(Mill)',
  [PaymentMethod.PayCent]: 'PayCent',
  [PaymentMethod.PSP_Neobanq]: 'PSP Neobanq',
  [PaymentMethod.PSP_NextPay]: 'PSP NextPay',
  [PaymentMethod.RoyalCoins]: 'RoyalCoins',
  [PaymentMethod.Ontario_CIBC]: 'Ontario(CIBC)',
  [PaymentMethod.Oceanlive_MB]: 'Oceanlive(MB)',
  [PaymentMethod.EclipCoin]: 'EclipCoin',
  [PaymentMethod.Famas_ING]: 'Famas(ING)',
  [PaymentMethod.CoinCash_Sent]: 'CoinCash (Sent)',
  [PaymentMethod.CORISMA_RAIFFEISEN]: 'CORISMA (RAIFFEISEN)',
  [PaymentMethod.Miracle_Montepio]: 'Miracle (Montepio)',
  [PaymentMethod.WiseNex]: 'WiseNex',
  [PaymentMethod.GRASPARAW_RAIFFEISEN]: 'GRASPARAW(RAIFFEISEN)',
  [PaymentMethod.CUBERKS_SANTANDER]: 'CUBERKS(SANTANDER)',
  [PaymentMethod.KEYTECHAGES_RAIFFEISEN]: 'KEYTECHAGES(RAIFFEISEN)',
  [PaymentMethod.Fábulas_Novo]: 'Fábulas (Novo)',
  [PaymentMethod.Centorina_BBVA]: 'Centorina(BBVA)',
  [PaymentMethod.CPS_BTC]: 'CPS(BTC)',
  [PaymentMethod.ECLETICSUND_ING]: 'ECLETICSUND(ING)',
  [PaymentMethod.Avangard_Unicredit]: 'Avangard(Unicredit)',
  [PaymentMethod.Keinter_Raiffeisen]: 'Keinter(Raiffeisen)',
  [PaymentMethod.Carisma_Novo]: 'Carisma(Novo)',
  [PaymentMethod.ErithExchange]: 'ErithExchange',
  [PaymentMethod.Randomsoft_SANTANDER]: 'Randomsoft(SANTANDER)',
  [PaymentMethod.Ferbalix_Raiffeisen]: 'Ferbalix(Raiffeisen)',
  [PaymentMethod.SOFTSOLCOMP_SANTANDER]: 'SOFTSOLCOMP(SANTANDER)',
  [PaymentMethod.CompSoftCar_CAIXA]: 'CompSoftCar(CAIXA)',
  [PaymentMethod.QUOTIDIAN_CRUSADE_ABANCA]: 'QUOTIDIAN CRUSADE(ABANCA)',
  [PaymentMethod.QUOTIDIAN_CRUSADE_BPI]: 'QUOTIDIAN CRUSADE(BPI)',
  [PaymentMethod.GesimaDecision_BBVA]: 'GesimaDecision(BBVA)',
  [PaymentMethod.PSP_BridgerPay]: 'PSP BridgerPay',
  [PaymentMethod.Pinolitex_Santander]: 'Pinolitex (Santander)',
  [PaymentMethod.Flamingo_Crusade]: 'Flamingo Crusade',
  [PaymentMethod.LTC]: 'LTC',
  [PaymentMethod.LIZER_TECHNOLOGY]: 'LIZER TECHNOLOGY S.R.L.',
  [PaymentMethod.Andolantra_SI]: 'Andolantra SI',
};

export const PaymentMethodListOptions = Object.entries(PaymentMethodLabel).map(
  ([value, label]) => ({
    value,
    label,
  }),
);
